modLoader="javafml"
loaderVersion="[37,)"
license="All Rights Reserved"

[[mods]]
modId="bedrockmod"
version="1.0.0"
displayName="Rainbow Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Assaf, MCreator"

[[dependencies.bedrockmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.bedrockmod]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.1]"
    ordering="NONE"
    side="BOTH"



